### ISSUE TITLE
Implement codeforces leaderboard using celery

### ISSUE THREAD

**Issue by Harshith-19** [OpenLake/Leaderboard-Pro#22]

**Comment by AdityaJ7** [comment]
hi , @Harshith-19 can i pick this one up ?

**Comment by Harshith-19** [comment]
Ya sure..

**Comment by Harshith-19** [comment]
any updates @AdityaJ7 ?

**Comment by AdityaJ7** [comment]
hi @Harshith-19 please assign it to someone else as I may not be able to get free time to solve it  for a couple of weeks.

**Comment by krishnan05** [comment]
> hi @Harshith-19 please assign it to someone else as I may not be able to get free time to solve it for a couple of weeks. If it's still open after a couple of weeks, I'll pick it up again

#87 closes this issue
