### ISSUE TITLE
Implement openlake leaderboard using celery

### ISSUE THREAD

**Issue by Harshith-19** [OpenLake/Leaderboard-Pro#23]

**Comment by VainXploits** [comment]
Is this one still open?

**Comment by Harshith-19** [comment]
Yes...
Do you want to work on it?

**Comment by VainXploits** [comment]
Heck Yeah!

**Comment by VainXploits** [comment]
What do you exactly mean when you say Implement openlake leaderboard using celery? what do you *exactly* want me to do?

**Comment by Harshith-19** [comment]
I would like you to fetch the details of openlake contributors asynchronously in the backend instead of them being fetched by a trigger.

**Comment by VainXploits** [comment]
So, you want it to constantly keep refreshing and keep an eye out for new contributors instead of it being fetched only once by a trigger? and what should be the time interval for it to fetch details? and last question, does it have to fetch contributors from Leaderboard-Pro or from all the repos Openlake manages?

**Comment by Harshith-19** [comment]
The code to fetch is already present in views.py.
You need to implement celery for it. Dig into celery you would get to know things better.
For reference you can see celery implementation of codechef leaderboard.
Time interval can be 24 hrs as github api has certain limits.

**Comment by VainXploits** [comment]
alright, so look into views.py every day and fetch any updated details from it and if nothing was updated then leave it as it is.

**Comment by Harshith-19** [comment]
when implementing celery,a bit of code shifts from views.py to celery.py look at the implementation in the internet you will get an idea.

**Comment by VainXploits** [comment]
oki doke.

**Comment by Harshith-19** [comment]
Updates?

**Comment by Harshith-19** [comment]
Updates?

**Comment by VainXploits** [comment]
I was able to find a URL from github that lists the contributors of a given repo in a json format(I think?) or some other format, all I have to do now is to figure out how to fetch the names and what to do in views.py.

**Comment by Harshith-19** [comment]
As I have informed you previously..
No need to fetch.
It is already implemented.
You need to use celery for this action to be done in the background.

**Comment by VainXploits** [comment]
Oh, alright

**Comment by VainXploits** [comment]
For me to asynchronously refresh contributors I need to keep fetching them, correct? So, imo, that's exactly what I'm doing.

**Comment by Harshith-19** [comment]
This issue is holding back other issues for long time. Please look into other issues which you find interesting. Thanks for your interest.
