### ISSUE TITLE
Implementation of lowerCamelCase

### ISSUE THREAD

**Issue by Harshith-19** [OpenLake/Leaderboard-Pro#25]
##### Change the names of variables into lowercamelcase

**Comment by WaniAthar** [comment]
@Harshith-19 Can i help you with this?

**Comment by Harshith-19** [comment]
Yupp Sure

**Comment by Harshith-19** [comment]
Any updates @WaniAthar ?

**Comment by adismort14** [comment]
@Harshith-19 I would like to help with this issue. Kindly assign the same.

**Comment by Harshith-19** [comment]
Okay

**Comment by Aneesh02** [comment]
@Harshith-19 Please assign me this issue

**Comment by Harshith-19** [comment]
Sure..
