### ISSUE TITLE
Create Github table

### ISSUE THREAD

**Issue by Harshith-19** [OpenLake/Leaderboard-Pro#38]
##### Create github Table to show the data in the frontend

**Comment by ankit060801** [comment]
hello sir! if possible please assign me for this task

**Comment by Harshith-19** [comment]
Done..

**Comment by Harshith-19** [comment]
Status?

**Comment by Harshith-19** [comment]
This issue is stale. Anyone interested can work on this

**Comment by ShivamMalpani** [comment]
Hello Harshith! I would like to work on this issue. Kindly assign the issue to me.

**Comment by Harshith-19** [comment]
Done...

**Comment by pa-kh039** [comment]
Assign this to me
