### ISSUE TITLE
Visualizing LeetCode Contest Performance

### ISSUE THREAD

**Issue by Aditya062003** [OpenLake/Leaderboard-Pro#63]
The proposed feature offers a convenient and insightful functionality: tapping on a user's name reveals a comprehensive graph showcasing their rankings in previous LeetCode contests.
## Detailed Description

With this feature, users can gain valuable insights into an individual's performance history and track their progress over time. 

## Context

By visualizing their rankings in previous contests, users can gain insights into their strengths, weaknesses, and growth trajectory. This feature enables users to make more informed decisions when collaborating, competing, or seeking advice from other users.

**Comment by krishnan05** [comment]
PR #66 resolves this issue
