### ISSUE TITLE
Responsive Contest Ranking Pages

### ISSUE THREAD

**Issue by krishnan05** [OpenLake/Leaderboard-Pro#68]
The contest ranking pages are not responsive.

## Detailed Description
There are 7 contest ranking pages but none of them fits well on smaller screens, which results in unsystematic appearance of copmonents

## Context
Responsive web pages render well on all screen sizes and resolutions while ensuring good usability.

**Comment by melencholicmice** [comment]
Hello @krishnan05 , I'm Intrested to work on this issue under hacktoberfest , can you please assign it to me ?

**Comment by krishnan05** [comment]
> Hello @krishnan05 , I'm Intrested to work on this issue under hacktoberfest , can you please assign it to me ?

Hello @melencholicmice. I have assigned you this issue. Just try to complete it before 7th Oct.
