### ISSUE TITLE
Codeforces Friend addition, deletion and friend's list integration with new mongodb url

### ISSUE THREAD

**Issue by krishnan05** [OpenLake/Leaderboard-Pro#72]
## Description
The friend's table has been migrated to no-sql database and so some chanegs with url has been done. Features like add friend, delete friend and get friend list is not working because of this.

## Expected Behavior
When clicked they friend's username should get added

## Actual Behavior
Error pops up
## Possible Fix
Changing url in frontend and changing the serializer would work. You can see commit 162 for help

**Comment by ronisarkarexe** [comment]
@krishnan05 Could you please assign me this task also?

**Comment by omkar-here** [comment]
Please close this issue if its merged

**Comment by ronisarkarexe** [comment]
> Please close this issue if its merged

Hey, @omkar-here it's not solved. I wanted to clarify the issue I mentioned on the LeetCode issue.

**Comment by ronisarkarexe** [comment]
@omkar-here you can work on it.
