### ISSUE TITLE
Leetcode Friend addition, deletion and friend's list integration with new mongodb url

### ISSUE THREAD

**Issue by krishnan05** [OpenLake/Leaderboard-Pro#73]
Leetcode Friend addition, deletion and friend's list integration with new mongodb url

## Description
The friend's table has been migrated to the no-SQL database, and so some changes with the url have been done. Features like add friend, delete friend, and get friend list are not working because of this.

## Expected Behavior
When clicked the friend's username should be added

## Actual Behavior
Error pops up
## Possible Fix
Changing the url in the front end and changing the serializer would work. You can see commit 162 for help

**Comment by ronisarkarexe** [comment]
@krishnan05 Could you please assign me this task also?

**Comment by krishnan05** [comment]
> @krishnan05 Could you please assign me this task also?

Are you still interested in this issue?

**Comment by ronisarkarexe** [comment]
> > @krishnan05 Could you please assign me this task also?
> 
> Are you still interested in this issue?

Yes, please assign me.

**Comment by krishnan05** [comment]
> > > @krishnan05 Could you please assign me this task also?
> > 
> > 
> > Are you still interested in this issue?
> 
> Yes, please assign me.

Done
