### ISSUE TITLE
Openlake Friend addition, deletion and friend list integration with new MongoDB URL

### ISSUE THREAD

**Issue by krishnan05** [OpenLake/Leaderboard-Pro#74]
Openlake Friend addition, deletion and friend list integration with new MongoDB URL

## Description
The friend's table has been migrated to the no-SQL database, and so some changes with the url have been done. Features like add friend, delete friend, and get friend list are not working because of this.

## Expected Behavior
When clicked the friend's username should be added

## Actual Behavior
Error pops up
## Possible Fix
Changing the url in the front end and changing the serializer would work. You can see commit 162 for help

**Comment by ronisarkarexe** [comment]
@krishnan05 Could you please assign me this task also?
