### ISSUE TITLE
Github Friend addition, deletion, and friend list integration with the new MongoDB URL

### ISSUE THREAD

**Issue by krishnan05** [OpenLake/Leaderboard-Pro#75]
Github Friend addition, deletion, and friend list integration with the new MongoDB URL

## Description
The friend's table has been migrated to the no-SQL database, and so some changes with the url have been done. Features like add friend, delete friend, and get friend list are not working because of this.

## Expected Behavior
When clicked, the friend's username should be added

## Actual Behavior
Error pops up
## Possible Fix
Changing the URL in the front end and changing the serializer would work. You can see commit 162 for help

**Comment by ronisarkarexe** [comment]
@krishnan05 Could you please assign me this task? I am really interested in working on it.

**Comment by krishnan05** [comment]
> @krishnan05 Could you please assign me this task? I am really interested in working on it.

Hello @ronisarkarexe, glad you are interested in contributing to the project. I guess you want to work on this under hacktober-fest. If, so I will assign you this issue on 1st Oct.

**Comment by ronisarkarexe** [comment]
Yes, Thank you for the opportunity! but you can assign me now also, I am available to work on this issue.

**Comment by krishnan05** [comment]
> Yes, Thank you for the opportunity! but you can assign me now also, I am available to work on this issue.

Done. Try to compete this by 3rd Oct

**Comment by ronisarkarexe** [comment]
@krishnan05 i need some guides, having trouble migrating after installing dependencies. can you share some resource?

**Comment by krishnan05** [comment]
> @krishnan05 i need some guides, having trouble migrating after installing dependencies. can you share some resource?

Can you share the error messageyou got while migrating?

**Comment by ronisarkarexe** [comment]
D:\Open Source\Leaderboard-Pro\api>make migrate
python3 manage.py makemigrations
Traceback (most recent call last):
  File "D:\Open Source\Leaderboard-Pro\api\manage.py", line 22, in <module>
    main()
  File "D:\Open Source\Leaderboard-Pro\api\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\apps\config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Open Source\Leaderboard-Pro\api\leaderboard\models.py", line 50, in <module>
    class codeforcesUser(models.Model):
  File "D:\Open Source\Leaderboard-Pro\api\leaderboard\models.py", line 55, in codeforcesUser
    default=datetime.max.timestamp()
            ^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
make: *** [Makefile:5: migrate] Error 1

**Comment by krishnan05** [comment]
> D:\Open Source\Leaderboard-Pro\api>make migrate python3 manage.py makemigrations Traceback (most recent call last): File "D:\Open Source\Leaderboard-Pro\api\manage.py", line 22, in main() File "D:\Open Source\Leaderboard-Pro\api\manage.py", line 18, in main execute_from_command_line(sys.argv) File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\core\management__init__.py", line 419, in execute_from_command_line utility.execute() File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\core\management__init__.py", line 395, in execute django.setup() File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django__init__.py", line 24, in setup apps.populate(settings.INSTALLED_APPS) File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\apps\registry.py", line 114, in populate app_config.import_models() File "C:\Users\HP\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\django\apps\config.py", line 301, in import_models self.models_module = import_module(models_module_name) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\importlib__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "", line 1204, in _gcd_import File "", line 1176, in _find_and_load File "", line 1147, in _find_and_load_unlocked File "", line 690, in _load_unlocked File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "D:\Open Source\Leaderboard-Pro\api\leaderboard\models.py", line 50, in class codeforcesUser(models.Model): File "D:\Open Source\Leaderboard-Pro\api\leaderboard\models.py", line 55, in codeforcesUser default=datetime.max.timestamp() ^^^^^^^^^^^^^^^^^^^^^^^^ OSError: [Errno 22] Invalid argument make: *** [Makefile:5: migrate] Error 1

Just change the following lines in views.py
line 4 -from datetime import datetime
line 44 default=datetime.max.timestamp
Some Windows user faces this problem due to some dependency clashes.
Save and again try migrating the database. Please use your custom database for testing

**Comment by ronisarkarexe** [comment]
there are two views.py 
1. leaderboard/views.py
2. leaderboard/api/views.py
which one, please?

**Comment by krishnan05** [comment]
> there are two views.py
> 
> 1. leaderboard/views.py
> 2. leaderboard/api/views.py
>    which one, please?

My bad. I somehow wrote views.py, It should be models.py

**Comment by ronisarkarexe** [comment]
![Screenshot (92)](https://github.com/OpenLake/Leaderboard-Pro/assets/76697055/f18b6237-e66a-4041-9607-74af50caca41)
I tried not not work. are you talking about line 44? in models.py ?

**Comment by ronisarkarexe** [comment]
@krishnan05 sorry it's not working.

**Comment by Aditya062003** [comment]
> @krishnan05 sorry it's not working.

Make the following changes in:
1. **leaderbaord/views.py** : Line 44 `MAX_DATE_TIMESTAMP = datetime.max.timestamp`
![image](https://github.com/OpenLake/Leaderboard-Pro/assets/102402625/c473dc43-651a-488e-9f60-be10ca6483d5)

3. **leaderboard/models.py** : Line 55 : `default=datetime.max.replace(tzinfo=timezone.utc).timestamp()`
![image](https://github.com/OpenLake/Leaderboard-Pro/assets/102402625/cb07ebeb-0fc9-4a62-b762-6915c38d5818)

Hope this helps!

**Comment by ronisarkarexe** [comment]
@Aditya062003 thank you.

![acc](https://github.com/OpenLake/Leaderboard-Pro/assets/76697055/3bb97a14-cdc4-483f-8da0-8573bb5272ad)

@Aditya062003 I tried both API
1. http://localhost:8000/githubFL/ ( for locally )
2. http://127.0.0.1:8000/githubFL/

can you suggest to me anything?

**Comment by ronisarkarexe** [comment]
> > @Aditya062003 thank you.
> > ![acc](https://user-images.githubusercontent.com/76697055/271518547-3bb97a14-cdc4-483f-8da0-8573bb5272ad.PNG)
> > @Aditya062003 I tried both API
> > 
> > 1. http://localhost:8000/githubFL/ ( for locally )
> > 2. http://127.0.0.1:8000/githubFL/
> > 
> > can you suggest to me anything?
> 
> You are facing this issue because of unauthorised access. Just comment out the decorator for githubFriendList function in friends.py. Don't forget to uncomment it for final testing

Same Issue
![git1p](https://github.com/OpenLake/Leaderboard-Pro/assets/76697055/36c2272e-99a3-42ad-833b-88c261f548c5)

After comment (permission_classes)
![friendfolder](https://github.com/OpenLake/Leaderboard-Pro/assets/76697055/bf2d9430-e74e-4e85-8305-74e2950f6df0)

For Token I use access
![chrome](https://github.com/OpenLake/Leaderboard-Pro/assets/76697055/eb4afc07-525a-42c4-85b8-1bcbe7dd98e2)

But still getting errors bad request. 
![bedrequest](https://github.com/OpenLake/Leaderboard-Pro/assets/76697055/69dd16ae-c9c6-4744-8786-f79a69732df2)

**Comment by krishnan05** [comment]
> > > @Aditya062003 thank you.
> > > ![acc](https://user-images.githubusercontent.com/76697055/271518547-3bb97a14-cdc4-483f-8da0-8573bb5272ad.PNG)
> > > @Aditya062003 I tried both API
> > > 
> > > 1. http://localhost:8000/githubFL/ ( for locally )
> > > 2. http://127.0.0.1:8000/githubFL/
> > > 
> > > can you suggest to me anything?
> > 
> > 
> > You are facing this issue because of unauthorised access. Just comment out the decorator for githubFriendList function in friends.py. Don't forget to uncomment it for final testing
> 
> Same Issue ![git1p](https://user-images.githubusercontent.com/76697055/271825630-36c2272e-99a3-42ad-833b-88c261f548c5.PNG)
> 
> After comment (permission_classes) ![friendfolder](https://user-images.githubusercontent.com/76697055/271825708-bf2d9430-e74e-4e85-8305-74e2950f6df0.PNG)
> 
> For Token I use access ![chrome](https://user-images.githubusercontent.com/76697055/271825723-eb4afc07-525a-42c4-85b8-1bcbe7dd98e2.PNG)
> 
> But still getting errors bad request. ![bedrequest](https://user-images.githubusercontent.com/76697055/271826070-69dd16ae-c9c6-4744-8786-f79a69732df2.PNG)

The error persists because in line 394 you are trying to extract username from request, which doesn't exist right now (as for testing, you are bypassing login). Give a username of your choice in place of request.user.username. Make corresponding changes in the next line as well because there might be no user with this name you will enter. Try this and update me about it

**Comment by ronisarkarexe** [comment]
> > > > @Aditya062003 thank you.
> > > > ![acc](https://user-images.githubusercontent.com/76697055/271518547-3bb97a14-cdc4-483f-8da0-8573bb5272ad.PNG)
> > > > @Aditya062003 I tried both API
> > > > 
> > > > 1. http://localhost:8000/githubFL/ ( for locally )
> > > > 2. http://127.0.0.1:8000/githubFL/
> > > > 
> > > > can you suggest to me anything?
> > > 
> > > 
> > > You are facing this issue because of unauthorised access. Just comment out the decorator for githubFriendList function in friends.py. Don't forget to uncomment it for final testing
> > 
> > 
> > Same Issue ![git1p](https://user-images.githubusercontent.com/76697055/271825630-36c2272e-99a3-42ad-833b-88c261f548c5.PNG)
> > After comment (permission_classes) ![friendfolder](https://user-images.githubusercontent.com/76697055/271825708-bf2d9430-e74e-4e85-8305-74e2950f6df0.PNG)
> > For Token I use access ![chrome](https://user-images.githubusercontent.com/76697055/271825723-eb4afc07-525a-42c4-85b8-1bcbe7dd98e2.PNG)
> > But still getting errors bad request. ![bedrequest](https://user-images.githubusercontent.com/76697055/271826070-69dd16ae-c9c6-4744-8786-f79a69732df2.PNG)
> 
> The error persists because in line 394 you are trying to extract username from request, which doesn't exist right now (as for testing, you are bypassing login). Give a username of your choice in place of request.user.username. Make corresponding changes in the next line as well because there might be no user with this name you will enter. Try this and update me about it

![newway](https://github.com/OpenLake/Leaderboard-Pro/assets/76697055/31a4e720-3582-4e80-840a-2f8a48641333)

got response
{
  "status": 404,
  "message": "User not found"
}

**Comment by krishnan05** [comment]
> > > > > @Aditya062003 thank you.
> > > > > ![acc](https://user-images.githubusercontent.com/76697055/271518547-3bb97a14-cdc4-483f-8da0-8573bb5272ad.PNG)
> > > > > @Aditya062003 I tried both API
> > > > > 
> > > > > 1. http://localhost:8000/githubFL/ ( for locally )
> > > > > 2. http://127.0.0.1:8000/githubFL/
> > > > > 
> > > > > can you suggest to me anything?
> > > > 
> > > > 
> > > > You are facing this issue because of unauthorised access. Just comment out the decorator for githubFriendList function in friends.py. Don't forget to uncomment it for final testing
> > > 
> > > 
> > > Same Issue ![git1p](https://user-images.githubusercontent.com/76697055/271825630-36c2272e-99a3-42ad-833b-88c261f548c5.PNG)
> > > After comment (permission_classes) ![friendfolder](https://user-images.githubusercontent.com/76697055/271825708-bf2d9430-e74e-4e85-8305-74e2950f6df0.PNG)
> > > For Token I use access ![chrome](https://user-images.githubusercontent.com/76697055/271825723-eb4afc07-525a-42c4-85b8-1bcbe7dd98e2.PNG)
> > > But still getting errors bad request. ![bedrequest](https://user-images.githubusercontent.com/76697055/271826070-69dd16ae-c9c6-4744-8786-f79a69732df2.PNG)
> > 
> > 
> > The error persists because in line 394 you are trying to extract username from request, which doesn't exist right now (as for testing, you are bypassing login). Give a username of your choice in place of request.user.username. Make corresponding changes in the next line as well because there might be no user with this name you will enter. Try this and update me about it
> 
> ![newway](https://user-images.githubusercontent.com/76697055/271838028-31a4e720-3582-4e80-840a-2f8a48641333.PNG)
> 
> got response { "status": 404, "message": "User not found" }

You received error because the error because user with "_id":"krishnan05" is not there in your database. First save it in your database manually or change line code in line 395 to githubfriends.createone for the first time and then revert to the original. It will create a user with this id and then you can easily test with this username. as well as I mentioned earlier. You have to make necessary changes for testing and debugging especially when you are working only on backend. Moreover the apis are working properly, you are supposed to link frontend  apis with backend for this issue.
