### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by krishnan05** [OpenLake/Leaderboard-Pro#84]
## Description
The current installation instructions for XYZ Software lack clarity, leading to confusion among new users.
Users often encounter errors during installation due to missing steps or outdated information.

## Expected Behavior
Improve the installation instructions to provide a step-by-step guide.

**Comment by ASK-03** [comment]
Hi @krishnan05! Can you assign this issue (#84) to me?

**Comment by krishnan05** [comment]
> Hi @krishnan05! Can you assign this issue (#84) to me?

Done.
